sudo: false
language: python
python: "3.5"
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36
  include:
    - python: 3.7
      env: TOX_ENV=py37
  include:
    - python: 3.7
      env: TOX_ENV=lint
  include:
    - python: 2.7
      env: TOX_ENV=lint
addons:
    apt:
        packages:
            - ed
install: pip install tox
script: tox -e $TOX_ENV
cache: pip
